exports.seed = async function (knex) {
  await knex("movies").del();

  await knex("movies").insert([
    {
      id: 1,
      title: "Midnight In Paris",
      runtime: 96,
      release_year: 2011,
      director: "Woody Allen",
    },
    {
      id: 2,
      title: "Titanic",
      runtime: 210,
      release_year: 1997,
      director: "James Cameron",
    },
    {
      id: 3,
      title: "From Paris With Love",
      runtime: 94,
      release_year: 2010,
      director: "Pierre Morel",
    },
    {
      id: 4,
      title: "Inception",
      runtime: 148,
      release_year: 2010,
      director: "Christopher Nolan",
    },
    {
      id: 5,
      title: "The Grand Budapest Hotel",
      runtime: 99,
      release_year: 2014,
      director: "Wes Anderson",
    },
    {
      id: 6,
      title: "The Matrix",
      runtime: 136,
      release_year: 1999,
      director: "Lana Wachowski & Lilly Wachowski",
    },
    {
      id: 7,
      title: "La La Land",
      runtime: 128,
      release_year: 2016,
      director: "Damien Chazelle",
    },
    {
      id: 8,
      title: "Parasite",
      runtime: 132,
      release_year: 2019,
      director: "Bong Joon-ho",
    },
    {
      id: 9,
      title: "Her",
      runtime: 126,
      release_year: 2013,
      director: "Spike Jonze",
    },
    {
      id: 10,
      title: "Whiplash",
      runtime: 106,
      release_year: 2014,
      director: "Damien Chazelle",
    },
    {
      id: 11,
      title: "The Social Network",
      runtime: 120,
      release_year: 2010,
      director: "David Fincher",
    },
    {
      id: 12,
      title: "Arrival",
      runtime: 116,
      release_year: 2016,
      director: "Denis Villeneuve",
    },
    {
      id: 13,
      title: "Eternal Sunshine of the Spotless Mind",
      runtime: 108,
      release_year: 2004,
      director: "Michel Gondry",
    },
    {
      id: 14,
      title: "Interstellar",
      runtime: 169,
      release_year: 2014,
      director: "Christopher Nolan",
    },
    {
      id: 15,
      title: "The Prestige",
      runtime: 130,
      release_year: 2006,
      director: "Christopher Nolan",
    },
  ]);
};
